{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a839d163-08d6-488b-a490-c2c1a6c913ff",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import gc\n",
    "import random\n",
    "import pandas as pd\n",
    "from datasets import load_dataset, DatasetDict, concatenate_datasets\n",
    "from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer\n",
    "from peft import LoraConfig, get_peft_model\n",
    "\n",
    "# ======================================================\n",
    "# 1. 基础配置\n",
    "# ======================================================\n",
    "model_name = \"Qwen/Qwen1.5-1.8B\"\n",
    "output_dir = \"Qwen1.8B_LCU_SFT\"\n",
    "batch_size = 2\n",
    "num_epochs = 4   # 你已经验证过最佳区间 4~6\n",
    "learning_rate = 2e-5\n",
    "\n",
    "print(f\"Loading tokenizer for {model_name}...\")\n",
    "tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)\n",
    "\n",
    "print(f\"Loading base model {model_name}...\")\n",
    "model = AutoModelForCausalLM.from_pretrained(\n",
    "    model_name,\n",
    "    trust_remote_code=True,\n",
    "    device_map=\"auto\",\n",
    ")\n",
    "\n",
    "if tokenizer.pad_token is None:\n",
    "    tokenizer.pad_token = tokenizer.eos_token\n",
    "    model.config.pad_token_id = tokenizer.eos_token_id\n",
    "\n",
    "# ======================================================\n",
    "# 2. LoRA 配置\n",
    "# ======================================================\n",
    "lora_config = LoraConfig(\n",
    "    r=8,\n",
    "    lora_alpha=16,\n",
    "    target_modules=[\"q_proj\", \"v_proj\", \"k_proj\", \"o_proj\"],\n",
    "    lora_dropout=0.05,\n",
    "    bias=\"none\",\n",
    "    task_type=\"CAUSAL_LM\",\n",
    ")\n",
    "model = get_peft_model(model, lora_config)\n",
    "print(\"LoRA injected successfully.\")\n",
    "\n",
    "# ======================================================\n",
    "# 3. 加载领域数据（必须已存在 jsonl 文件）\n",
    "# ======================================================\n",
    "domain_files = {\n",
    "    \"staytime\": \"staytime_prediction.jsonl\",\n",
    "    \"top_comment\": \"kuaiComt_top_comment_prediction_data.jsonl\",\n",
    "    \"interaction\": \"user_comment_interaction_prediction.jsonl\"\n",
    "}\n",
    "\n",
    "datasets = []\n",
    "min_size = float('inf')\n",
    "\n",
    "print(\"\\nLoading domain datasets...\")\n",
    "for name, file in domain_files.items():\n",
    "    ds = load_dataset(\"json\", data_files=file, split=\"train\")\n",
    "    min_size = min(min_size, len(ds))\n",
    "    datasets.append(ds)\n",
    "    print(f\"[OK] {name}: {len(ds)} samples\")\n",
    "\n",
    "# ======================================================\n",
    "# 4. 加载 Alpaca-GPT4 通用数据\n",
    "# ======================================================\n",
    "alpaca = load_dataset(\"json\", data_files=\"alpaca_data.json\", split=\"train\")\n",
    "print(f\"[OK] Alpaca: {len(alpaca)} samples\")\n",
    "\n",
    "def format_data(ex):\n",
    "    prompt = ex.get(\"instruction\",\"\") + \"\\n\" + ex.get(\"input\",\"\")\n",
    "    return {\"prompt\": prompt.strip(), \"completion\": ex.get(\"output\",\"\")}\n",
    "\n",
    "alpaca = alpaca.map(format_data, remove_columns=alpaca.column_names)\n",
    "\n",
    "# 取比例 1:1:1:3\n",
    "datasets = [ds.shuffle(seed=42).select(range(min_size)) for ds in datasets]\n",
    "alpaca = alpaca.shuffle(seed=42).select(range(min_size * 3))\n",
    "\n",
    "combined = concatenate_datasets(datasets + [alpaca])\n",
    "print(f\"\\n[✓] Total SFT Training Samples = {len(combined)}\")\n",
    "\n",
    "# ======================================================\n",
    "# 5. 划分训练/验证集\n",
    "# ======================================================\n",
    "dataset = combined.train_test_split(test_size=0.05, seed=42)\n",
    "print(f\"Train = {len(dataset['train'])}, Validation = {len(dataset['test'])}\")\n",
    "\n",
    "# ======================================================\n",
    "# 6. Tokenization\n",
    "# ======================================================\n",
    "def tokenize(examples):\n",
    "    texts = []\n",
    "    for p, c in zip(examples[\"prompt\"], examples[\"completion\"]):\n",
    "        text = f\"<|im_start|>user\\n{p}<|im_end|>\\n<|im_start|>assistant\\n{c}<|im_end|>\"\n",
    "        texts.append(text)\n",
    "\n",
    "    tokenized = tokenizer(\n",
    "        texts,\n",
    "        padding=\"max_length\",\n",
    "        truncation=True,\n",
    "        max_length=512\n",
    "    )\n",
    "    tokenized[\"labels\"] = tokenized[\"input_ids\"].copy()\n",
    "    return tokenized\n",
    "\n",
    "dataset = dataset.map(tokenize, batched=True, remove_columns=[\"prompt\", \"completion\"])\n",
    "\n",
    "# ======================================================\n",
    "# 7. Trainer 参数\n",
    "# ======================================================\n",
    "training_args = TrainingArguments(\n",
    "    output_dir=output_dir,\n",
    "    per_device_train_batch_size=batch_size,\n",
    "    gradient_accumulation_steps=8,\n",
    "    num_train_epochs=num_epochs,\n",
    "    learning_rate=learning_rate,\n",
    "    save_steps=200,\n",
    "    eval_steps=200,\n",
    "    logging_steps=50,\n",
    "    evaluation_strategy=\"steps\",\n",
    "    save_total_limit=2,\n",
    "    report_to=\"none\"\n",
    ")\n",
    "\n",
    "trainer = Trainer(\n",
    "    model=model,\n",
    "    args=training_args,\n",
    "    train_dataset=dataset[\"train\"],\n",
    "    eval_dataset=dataset[\"test\"],\n",
    "    tokenizer=tokenizer\n",
    ")\n",
    "\n",
    "# ======================================================\n",
    "# 8. 开始训练\n",
    "# ======================================================\n",
    "print(\"\\n🔥 Start Fine-tuning...\\n\")\n",
    "trainer.train()\n",
    "\n",
    "model.save_pretrained(output_dir)\n",
    "tokenizer.save_pretrained(output_dir)\n",
    "\n",
    "print(\"\\n✅ Training Completed Successfully!\")\n",
    "print(f\"Fine-tuned model saved at: {output_dir}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
